// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (id, created_at, updated_at, title, url, description, published_at, feed_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const getAllPostsFromFeed = `-- name: GetAllPostsFromFeed :many
SELECT feeds.name AS feed_name, posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
FROM posts
INNER JOIN feeds ON feeds.id = posts.feed_id
WHERE posts.feed_id = $1
ORDER BY posts.published_at DESC
`

type GetAllPostsFromFeedRow struct {
	FeedName    string
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) GetAllPostsFromFeed(ctx context.Context, feedID uuid.UUID) ([]GetAllPostsFromFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostsFromFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsFromFeedRow
	for rows.Next() {
		var i GetAllPostsFromFeedRow
		if err := rows.Scan(
			&i.FeedName,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedPosts = `-- name: GetFollowedPosts :many
WITH user_followed_feeds AS (
    SELECT feeds.name AS feed_name, feeds.id AS feed_id
    FROM feed_follows
    INNER JOIN users ON feed_follows.user_id = users.id
    INNER JOIN feeds ON feed_follows.feed_id = feeds.id
    WHERE feed_follows.user_id = $1
)
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, user_followed_feeds.feed_name
FROM posts
INNER JOIN user_followed_feeds ON user_followed_feeds.feed_id = posts.feed_id
ORDER BY posts.published_at DESC
LIMIT $2
`

type GetFollowedPostsParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetFollowedPostsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
	FeedName    string
}

// Get feeds being followed...
// ...get all posts from those feeds
func (q *Queries) GetFollowedPosts(ctx context.Context, arg GetFollowedPostsParams) ([]GetFollowedPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedPosts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowedPostsRow
	for rows.Next() {
		var i GetFollowedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastPostTimestamp = `-- name: GetLastPostTimestamp :one
SELECT posts.published_at
FROM posts
INNER JOIN feeds ON feeds.id = posts.feed_id
WHERE posts.feed_id = $1
ORDER BY posts.published_at DESC
LIMIT 1
`

func (q *Queries) GetLastPostTimestamp(ctx context.Context, feedID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastPostTimestamp, feedID)
	var published_at time.Time
	err := row.Scan(&published_at)
	return published_at, err
}

const getPostById = `-- name: GetPostById :one
SELECT posts.title, posts.description, posts.published_at, posts.Url
FROM posts
WHERE posts.id = $1
`

type GetPostByIdRow struct {
	Title       string
	Description string
	PublishedAt time.Time
	Url         string
}

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Url,
	)
	return i, err
}

const getPostsFromFeed = `-- name: GetPostsFromFeed :many
SELECT feeds.name AS feed_name, posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
FROM posts
INNER JOIN feeds ON feeds.id = posts.feed_id
WHERE posts.feed_id = $1
ORDER BY posts.published_at DESC
LIMIT $2
`

type GetPostsFromFeedParams struct {
	FeedID uuid.UUID
	Limit  int32
}

type GetPostsFromFeedRow struct {
	FeedName    string
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) GetPostsFromFeed(ctx context.Context, arg GetPostsFromFeedParams) ([]GetPostsFromFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsFromFeed, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsFromFeedRow
	for rows.Next() {
		var i GetPostsFromFeedRow
		if err := rows.Scan(
			&i.FeedName,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const numPostsSinceTimestamp = `-- name: NumPostsSinceTimestamp :one
SELECT COUNT(*)
FROM posts
WHERE posts.feed_id = $1
  AND posts.published_at > $2
`

type NumPostsSinceTimestampParams struct {
	FeedID      uuid.UUID
	PublishedAt time.Time
}

func (q *Queries) NumPostsSinceTimestamp(ctx context.Context, arg NumPostsSinceTimestampParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, numPostsSinceTimestamp, arg.FeedID, arg.PublishedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
