// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: search.sql

package database

import (
	"context"
	"time"
)

const searchPostTitles = `-- name: SearchPostTitles :many
SELECT feeds.name AS feed_name, posts.title, posts.published_at FROM posts
INNER JOIN feeds on feeds.id = posts.feed_id
WHERE posts.title ILIKE $1
ORDER BY posts.published_at DESC
`

type SearchPostTitlesRow struct {
	FeedName    string
	Title       string
	PublishedAt time.Time
}

func (q *Queries) SearchPostTitles(ctx context.Context, title string) ([]SearchPostTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostTitles, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostTitlesRow
	for rows.Next() {
		var i SearchPostTitlesRow
		if err := rows.Scan(&i.FeedName, &i.Title, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
